version: '3.8'
services:
  db:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=main
      - MYSQL_ROOT_PASSWORD=qwerty123456
    ports:
      - '3306:3306'

  backend:
    build: ../../services/server
    env_file:
      - ../../services/server/.env.dev
    restart: always
    depends_on:
      - db
    ports:
      - '5000:5000'

  frontend:
    build: ../../services/client
    env_file:
      - ../../services/client/.env.dev
    restart: always
    depends_on:
      - backend
    ports:
      - '3000:3000'
